apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Release.Name | quote }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name | quote }}
        image: "{{ .Values.image.repository }}:{{ default "latest" .Values.image.tag }}"
        {{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- end}}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}
