{{- $globalContext := . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Release.Name | quote }}
  annotations:
  {{- if .Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls: 
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ . }}
    {{- end }}
    secretName: "{{ .Release.Name }}-tls"
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ $globalContext.Release.Name | quote }}
          servicePort: {{ $globalContext.Values.service.externalPort }}
  {{- end}}
