apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
  - name: {{ .Values.service.name | quote }}
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ .Release.Name | quote }}
